export const BUTTON_TEXT_SIZE = 20;
export const BUTTON_CANCEL_SIZE = BUTTON_TEXT_SIZE + 4;
export const BUTTON_HEIGHT = BUTTON_CANCEL_SIZE + 1;
export const BUTTON_PADDING = 3;
export const BUTTON_MARGIN = 3;
export const BUTTON_SPACING = BUTTON_MARGIN + BUTTON_PADDING;